describe('My Listings page', () => {
    it('should allow users to edit their listings', () => {
      cy.visit('/')
      cy.login("seppo@raty.com", "test")
      cy.url().should('be.equal',`${Cypress.config("baseUrl")}/`)
      cy.get('[data-testid="add"] > a').click()
      cy.get('#title').type("Valid Input Test")
      cy.get('#description').type("Description...")
      cy.get('#price').type("200.22")
      cy.get('#image').type("test")
      cy.get('#category-select').click()
      cy.get('.MuiList-root > [tabindex="0"]').click()
      cy.get('.button').click()
      cy.url().should('be.equal',`${Cypress.config("baseUrl")}/`)
      cy.get('[data-testid=title]').should('contain', 'Valid Input Test')
      cy.get('[data-testid="myitems"] > a').click()
      cy.contains('Valid Input Test')
      .parent('.item__info')
      .parent('.card')
      .within(() => {
        cy.get('.item__actions > :nth-child(1)').click()
      })
      cy.get('#edit-title').focus().clear()
      cy.get('#edit-title').type("Edit Title Test")
      cy.get('#edit-description').focus().clear()
      cy.get('#edit-description').type("Edit Description Test")
      cy.get('#edit-price').focus().clear()
      cy.get('#edit-price').type("1111.11")
      cy.get('.item__actions > :nth-child(1)').contains('Save').click()
      cy.get('[data-testid=title]').should('contain', 'Edit Title Test')
      cy.get('[data-testid=description]').should('contain', 'Edit Description Test')
      cy.get('[data-testid=price]').should('contain', '1111.11')
    })
    it('should allow users to delete their listings', () => {
      cy.visit('/')
      cy.login("seppo@raty.com", "test")
      cy.url().should('be.equal',`${Cypress.config("baseUrl")}/`)
      cy.get('[data-testid="myitems"] > a').click()
      cy.contains('Edit Title Test')
      .parent('.item__info')
      .parent('.card')
      .within(() => {
        cy.get('.item__actions > .button--danger').click()
      })
      cy.get('h2 > :nth-child(2)').click()
      cy.get('[data-testid="title"]')
        .should('not.contain', 'Edit Title Test')
    })
  })